language: R
sudo: false
cache: packages

os:
  - linux
#  - osx

before_install:
  - easy_install distribute
  - pip install -r requirements.txt

r_packages:
  - reticulate
  - magrittr
  - rjson
  - yaml
  - knitr
  - bookdown
  - githubinstall

r_github_packages:
  - datawookie/emayili

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'devtools::install()'
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAT
  keep_history: true
  local-dir: docs
  on:
    branch: master
