language: r
warnings_are_errors: false
sudo: required
dist: trusty

cache:
  - packages
  - pip

os:
  - linux
#  - osx

before_install:
  - pip install --user numpy requests bs4 pyyaml

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'devtools::install()'
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAT
  keep_history: true
  local-dir: docs
  on:
    branch: master
