on: [push, pull_request]
#  schedule:
#    - cron:  '0 0 * * FRI'

name: Weekly test

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: wei/curl@master
        with:
          args: https://httpbin.org/get
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("rcmdcheck")
        shell: Rscript {0}

      - name: Install system dependencies
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          Rscript -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"

      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ matrix.config.r }}-${{ hashFiles('depends.Rds') }}
          restore-keys: ${{ runner.os }}-r-${{ matrix.config.r }}-

      - name: Install package
        run: R CMD INSTALL .

      - name: Testing with Code coverage
        run: Rscript -e "covr::codecov()"

