on: [push, pull_request]
#  schedule:
#    - cron:  '0 0 * * FRI'

name: Weekly test

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: wei/curl@master
        with:
          args: https://httpbin.org/get
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      - name: Install python libraries
        run: pip install requests bs4 pyyaml

      - name: Install system dependencies
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          sudo apt-get install libcurl4-openssl-dev
          Rscript -e "install.packages(c('remotes', 'rcmdcheck'))"
          Rscript -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"

      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("rcmdcheck")
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .

      - name: Testing with Code coverage
        run: Rscript -e "covr::codecov()"
